/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation("io.dropwizard:dropwizard-core:4.0.11") 
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
